development:
  sessions:
    default:
      database: ncia_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: ncia_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
